### ISSUE TITLE
public template not work

### ISSUE THREAD

**Issue by SaifSalah** [al-jazeera/jobs#20]
public template not working correctly ..

there is issue with : 

navbar and footer at default layout have a wrong must should be : 

@include('layouts.public.navbar')
and 
@include('layouts.public.footer')

and there is issue with : 
css files not found 

@gozyasi

**Comment by gozyasi** [comment]
Thanks for letting me know, I do highly apologize for that.. 
I'm working on resolving those issues now..

**Comment by gozyasi** [comment]
@SaifSalah I have fixed the mentioned issues, please check it at #22

**Comment by SaifSalah** [comment]
ok bro , thank you i'll check

**Comment by fiftysoft** [comment]
@SaifSalah @gozyasi good job team the issue well be closed
